export const professions = [
	'Labour',
	'Carpenter',
	'Car Mechanic',
	'Painter(Car)',
	'Dentor(Car)',
	'Electrician',
	'Painter',
	'Rajmistri',
	'CCTV camera',
	'Milkman',
	'House Cleaning',
	'Laundry',
	'Hair Dresser',
	'Maid',
	'Plumber',
	'Driver',
	'Car Cleaning',
	'Gardner',
	'Gym Trainer',
	'POP Ceiling',
	'Pest Control',
	'Boring',
	'AC Servicing',
	'Car Repair Centre',
	'Cook',
	'Flower Delivery',
	'Tailor',
	'Mechanic(Television)',
	'Accountant',
	'Barber',
	'Construction',
	'Office Work',
	'Manager',
	'Delivery Boy',
	'Graphic and web designer',
	'Video Editing',
	'Pharma',
	'Finance',
	'Laundry',
	'Teacher',
	'Marketing',
	'General Repairs',
	'Wiring',
];
